---
abstract: 'handles interactive (and non-interactive) process invocation'
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Test::Exception: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Command-Interactive
requires:
  Expect: 0
  Moose: 0
version: 0.2
