---
abstract: unknown
author:
  - 'binary.com <perl@binary.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Command-Interactive
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/binary-com/perl-command-interactive.git
version: '1.1'
